TOTP_Web/TOTP_Web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include(('todo_app.urls', 'home'), namespace='todo_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TOTP_Web/todo_app/urls.py
# todo_list/todo_app/urls.py
from django.urls import path
# todo_list/todo_app/urls.py
from todo_app import views

app_name = 'todo_app'
urlpatterns = [
    path("todo_list/",
         views.ListListView.as_view(), name="todo_list"),
    path("list/<int:list_id>/",
         views.ItemListView.as_view(), name="list"),
    # CRUD patterns for ToDoLists
    path("list/add/", views.ListCreate.as_view(), name="list_add"),
    path(
        "list/<int:pk>/delete/", views.ListDelete.as_view(), name="list_delete"
    ),
    # CRUD patterns for ToDoItems
    path(
        "list/<int:list_id>/item/add/",
        views.ItemCreate.as_view(),
        name="item_add",
    ),
    path(
        "list/<int:list_id>/item/<int:pk>/",
        views.ItemUpdate.as_view(),
        name="item_update",
    ),
    path(
        "list/<int:list_id>/item/<int:pk>/delete/",
        views.ItemDelete.as_view(),
        name="item_delete",
    ),
]

TOTP_Web/users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login_request, name="login"),
    path('', views.login_request, name="login"),
    path('otp/<int:id>/', views.otp_request, name="otp"),
    path('homepage/', views.homepage.as_view(), name='homepage'),
    path('register/', views.register_request, name="register"),
    path('logout/', views.logout_request, name="logout"),
    # path('', TemplateView.as_view(template_name='Login/home.html'), name='homepage'),
    path('change_password/',auth_views.PasswordChangeView.as_view(
            template_name='ResetPassword/reset.html',
            success_url = '/'
        ), name='change_password'
    ),
    
]

TOTP_Web/users/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models


class OTP(models.Model):
    otp = models.CharField(default='', max_length=15, verbose_name='otp')
    user_id = models.IntegerField(verbose_name='user_id', unique=True)
    serial = models.CharField(default ='', max_length=10, verbose_name='serial', unique=True)

TOTP_Web/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from users.models import OTP


# Create your forms here.
class LoginForm(forms.Form):
    username = forms.CharField(required=True, max_length=120)
    password = forms.CharField(required=True, min_length=6)


class OTPForm(forms.Form):
    otp = forms.CharField(required=True, min_length=6)


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    serial = forms.CharField(required=True, max_length=10, min_length=10)
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            otp_obj = OTP(user_id=user.id)
            otp_obj.serial = self.cleaned_data['serial']
            otp_obj.save()
        return user

TOTP_Web/users/views.py
import datetime
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from .genOTP import genOTP
from .forms import RegisterForm, OTPForm, LoginForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from .models import OTP


def register_request(request):
    storage = messages.get_messages(request)
    storage.used = True
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("users:login")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = RegisterForm()
    return render(request=request, template_name="Register/register.html", context={"register_form": form})


def login_request(request):
    storage = messages.get_messages(request)
    storage.used = True
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                otp_user = OTP.objects.get(user_id=user.id)
                _user = User.objects.get(id=user.id)
                otp_user.otp = genOTP(otp_user.serial)
                otp_user.save()
                storage = messages.get_messages(request)
                storage.used = True
                return redirect("users:otp", int(user.id))
            else:
                messages.error(request, "No exits account with this username or this password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="Login/login.html", context={"login_form": form})


def otp_request(request, id):
    storage = messages.get_messages(request)
    storage.used = True
    otp_dt = OTP.objects.get(user_id=id)
    user = User.objects.get(id=id)
    print(genOTP(otp_dt.serial))
    if request.method == "POST":
        form = OTPForm(request.POST)
        if form.is_valid():
            otp = form.cleaned_data.get('otp')
            if otp == genOTP(otp_dt.serial):
                otp_dt.otp = otp
                otp_dt.save()
                login(request, user)
                messages.info(request, "You login success !")
                storage = messages.get_messages(request)
                storage.used = True
                return redirect("users:homepage")
            else:
                messages.error(request, "Invalid OTP!")
        else:
            messages.error(request, "Invalid OTP!")
    form = OTPForm()
    return render(request=request, template_name="Login/totp.html", context={"otp_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    
    storage = messages.get_messages(request)
    storage.used = True
    return redirect("users:login")


class homepage(LoginRequiredMixin, TemplateView):
    template_name = 'Login/home.html'

TOTP_Web/users/templates/Login/home.html
{% extends 'homepage/base.html' %}
{% load static %} 
{% block title %}Profile{% endblock %}
{% block cssblock %} {% endblock %} 
{% block content %}

<div class="LoginSuccess">
    <div class="container">
        <h1>Profile</h1>
        <p>Xin chao {{ user.username }}</p>
        <p><a href="{% url 'todo_app:todo_list' %}">My Todo List</a></p>
        <p><a href="{% url 'users:change_password' %}">Change Password</a></p>
    </div>

</div>
{% endblock %} {% block jsblock %} {% endblock %}

TOTP_Web/users/templates/Login/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock %}
{% block cssblock %}
<link rel="stylesheet" href="{% static 'homepage/css/login.css' %}" type="text/css">
{% endblock %}
{% block content %}

<div class="wapper">
    <div class="wapper-heading">
    <h1>Đăng nhập</h1>
    </div>
    {% for message in messages %}
    <div class="container-fluid p-0">
      <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="True">&times;</span>
        </button>
        {{ message }}
      </div>
    </div>
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        {{ login_form|crispy }}
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>

</div>
{% endblock %}

TOTP_Web/users/templates/Login/totp.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Xác thực OTP{% endblock %}
{% block cssblock %}

<link rel="stylesheet" href="{% static 'homepage/css/signup.css' %}" type="text/css">
{% endblock %}
{% block content %}

<div class="wapper" >
    <div class="wapper-heading" style="padding-bottom: 30px">
    <h1 style="text-size: 5px;">Nhập OTP</h1>
    </div>
    {% for message in messages %}
    <div class="container-fluid p-0">
      <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="True">&times;</span>
        </button>
        {{ message }}
      </div>
    </div>
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        <input id="otp" type="text" name="otp">

		<button class="btn btn-primary mt-4" type="submit">Xác nhận</button>
    </form>
</div>
{% endblock %}