TOTP_Web/TOTP_Web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include(('todo_app.urls', 'home'), namespace='todo_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TOTP_Web/todo_app/urls.py
# todo_list/todo_app/urls.py
from django.urls import path
# todo_list/todo_app/urls.py
from todo_app import views

app_name = 'todo_app'
urlpatterns = [
    path("todo_list/",
         views.ListListView.as_view(), name="todo_list"),
    path("list/<int:list_id>/",
         views.ItemListView.as_view(), name="list"),
    # CRUD patterns for ToDoLists
    path("list/add/", views.ListCreate.as_view(), name="list_add"),
    path(
        "list/<int:pk>/delete/", views.ListDelete.as_view(), name="list_delete"
    ),
    # CRUD patterns for ToDoItems
    path(
        "list/<int:list_id>/item/add/",
        views.ItemCreate.as_view(),
        name="item_add",
    ),
    path(
        "list/<int:list_id>/item/<int:pk>/",
        views.ItemUpdate.as_view(),
        name="item_update",
    ),
    path(
        "list/<int:list_id>/item/<int:pk>/delete/",
        views.ItemDelete.as_view(),
        name="item_delete",
    ),
]

TOTP_Web/users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login_request, name="login"),
    path('', views.login_request, name="login"),
    path('otp/<int:id>/', views.otp_request, name="otp"),
    path('homepage/', views.homepage.as_view(), name='homepage'),
    path('register/', views.register_request, name="register"),
    path('logout/', views.logout_request, name="logout"),
    # path('', TemplateView.as_view(template_name='Login/home.html'), name='homepage'),
    path('change_password/',auth_views.PasswordChangeView.as_view(
            template_name='ResetPassword/reset.html',
            success_url = '/'
        ), name='change_password'
    ),
    
]

TOTP_Web/templates/homepage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Block -->
    <link rel="stylesheet" href="{% static 'homepage/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'homepage/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'homepage/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'homepage/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'homepage/css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'homepage/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'homepage/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'homepage/css/style.css' %}" type="text/css"> {% block cssblock %} {% endblock %}
</head>

<body>
    <div>
        {% include 'homepage/navbar.html' %} 
    </div>
    {% block content %} {% endblock %} 

    <script src="{% static 'homepage/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'homepage/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'homepage/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'homepage/js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'homepage/js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'homepage/js/mixitup.min.js' %}"></script>
    <script src="{% static 'homepage/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'homepage/js/main.js' %}"></script>

    {% block jsblock %} {% endblock %}
</body>

</html>

TOTP_Web/templates/homepage/navbar.html
<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Humberger Begin -->
<div class="humberger__menu__overlay"></div>
<div class="humberger__menu__wrapper">
    <div class="humberger__menu__logo">
        <a href="#"><img src="img/logo.png" alt=""></a>
    </div>
    <div class="humberger__menu__widget">

        {% if not user.is_authenticated %}
        <div class="header__top__right__auth">
            <a href="{% url 'users:login' %}"><i class="fa fa-user"></i>Login</a>
        </div>
        <div class="header__top__right__auth">
            <a href="{% url 'users:register' %}"><i class="fa fa-user"></i>Register</a>
        </div>
        <div class="header__top__right__auth">
            <a href="/admin"><i class="fa fa-user"></i>Admin Login</a>
        </div>
        {% else %}
        <div class="header__top__right__auth">
            <a href="{% url 'users:homepage' %}"><i class="fa fa-user"></i>Profile</a>
        </div>
        <div class="header__top__right__auth"> </div>
        <div class="header__top__right__auth">
            <a href="{% url 'users:logout' %}"><i class="fa fa-sign-out"></i>Logout</a>
        </div>
        {% endif %}
    </div>
    <nav class="humberger__menu__nav mobile-menu">
        <ul>
            <li><a href="#">Pages</a>
                <ul class="header__menu__dropdown">
                    <li><a href="{% url 'todo_app:todo_list' %}">My Todo List</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="mobile-menu-wrap"></div>
    <div class="header__top__right__social">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
    </div>
    <div class="humberger__menu__contact">
        <ul>
            <li><i class="fa fa-envelope"></i> admin@gmail.com</li>
            <li>Welcome to the page</li>
        </ul>
    </div>
</div>
<!-- Humberger End -->

<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="header__top__left">
                        <ul>
                            <li><i class="fa fa-envelope"></i>admin@gmail.com</li>
                            <li>Welcome to the page</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="header__top__right">
                        <div class="header__top__right__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </div>
                        {% if not user.is_authenticated %}
                        <div class="header__top__right__auth">
                            <a href="{% url 'users:login' %}"><i class="fa fa-user"></i>Login</a>
                        </div>
                        <div class="header__top__right__auth">
                            <a href="{% url 'users:register' %}"><i class="fa fa-user"></i>Register</a>
                        </div>
                        <div class="header__top__right__auth">
                            <a href="/admin"><i class="fa fa-user"></i>Admin</a>
                        </div>
                        {% else %}
                        <div class="header__top__right__auth">
                            <a href="{% url 'users:homepage' %}"><i class="fa fa-user"></i>Profile</a>
                        </div>
                        <div class="header__top__right__auth"> </div>
                        <div class="header__top__right__auth">
                            <a href="{% url 'users:logout' %}"><i class="fa fa-sign-out"></i>Logout</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <nav class="header__menu">
                    <ul>
                        <li><a href="#">Pages</a>
                            <ul class="header__menu__dropdown">
                                <li><a href="{% url 'todo_app:todo_list' %}">My Todo List</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <div class="humberger__open">
            <i class="fa fa-bars"></i>
        </div>
    </div>
</header>
<!-- Header Section End -->