TOTP_Web/TOTP_Web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include(('todo_app.urls', 'home'), namespace='todo_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TOTP_Web/todo_app/urls.py
# todo_list/todo_app/urls.py
from django.urls import path
# todo_list/todo_app/urls.py
from todo_app import views

app_name = 'todo_app'
urlpatterns = [
    path("todo_list/",
         views.ListListView.as_view(), name="todo_list"),
    path("list/<int:list_id>/",
         views.ItemListView.as_view(), name="list"),
    # CRUD patterns for ToDoLists
    path("list/add/", views.ListCreate.as_view(), name="list_add"),
    path(
        "list/<int:pk>/delete/", views.ListDelete.as_view(), name="list_delete"
    ),
    # CRUD patterns for ToDoItems
    path(
        "list/<int:list_id>/item/add/",
        views.ItemCreate.as_view(),
        name="item_add",
    ),
    path(
        "list/<int:list_id>/item/<int:pk>/",
        views.ItemUpdate.as_view(),
        name="item_update",
    ),
    path(
        "list/<int:list_id>/item/<int:pk>/delete/",
        views.ItemDelete.as_view(),
        name="item_delete",
    ),
]

TOTP_Web/users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login_request, name="login"),
    path('', views.login_request, name="login"),
    path('otp/<int:id>/', views.otp_request, name="otp"),
    path('homepage/', views.homepage.as_view(), name='homepage'),
    path('register/', views.register_request, name="register"),
    path('logout/', views.logout_request, name="logout"),
    # path('', TemplateView.as_view(template_name='Login/home.html'), name='homepage'),
    path('change_password/',auth_views.PasswordChangeView.as_view(
            template_name='ResetPassword/reset.html',
            success_url = '/'
        ), name='change_password'
    ),
    
]

TOTP_Web/todo_app/models.py
from django.utils import timezone

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


def one_week_hence():
    return timezone.now() + timezone.timedelta(days=7)


class ToDoList(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=100, unique=True)

    def get_absolute_url(self):
        return reverse("todo_app:list", args=[self.id])

    def __str__(self):
        return self.title


class ToDoItem(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(default=one_week_hence)
    todo_list = models.ForeignKey(ToDoList, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse(
            "todo_app:item_update", args=[str(self.todo_list.id), str(self.id)]
        )

    def __str__(self):
        return f"{self.title}: due {self.due_date}"

    class Meta:
        ordering = ["due_date"]

TOTP_Web/todo_app/views.py
# todo_list/todo_app/views.py
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.shortcuts import redirect
from .models import ToDoItem, ToDoList


class ListListView(ListView):
    model = ToDoList
    template_name = "todo_app/index.html"
    def get_queryset(self):
        return ToDoList.objects.filter(user=self.request.user)


class ItemListView(ListView):
    model = ToDoItem
    template_name = "todo_app/todo_list.html"

    def get_queryset(self):
        return ToDoItem.objects.filter(todo_list_id=self.kwargs["list_id"])

    def get_context_data(self):
        context = super().get_context_data()
        context["todo_list"] = ToDoList.objects.get(id=self.kwargs["list_id"])
        return context


class ListCreate(CreateView):
    model = ToDoList
    fields = ["title"]

    def get_context_data(self):
        context = super(ListCreate, self).get_context_data()
        context["title"] = "Add a new list"
        return context

    def form_valid(self, form):
        todo_list = form.save(commit=False)
        todo_list.user = self.request.user
        todo_list.save()
        
        return redirect("todo_app:list", int(todo_list.id))

    def get_success_url(self):
        return reverse("todo_app:list", args=[self.object.todo_list_id])


class ItemCreate(CreateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    def get_initial(self):
        initial_data = super(ItemCreate, self).get_initial()
        todo_list = ToDoList.objects.get(id=self.kwargs["list_id"])
        initial_data["todo_list"] = todo_list
        return initial_data

    def get_context_data(self):
        context = super(ItemCreate, self).get_context_data()
        todo_list = ToDoList.objects.get(id=self.kwargs["list_id"])
        context["todo_list"] = todo_list
        context["title"] = "Create a new item"
        return context

    def get_success_url(self):
        return reverse("todo_app:list", args=[self.object.todo_list_id])


class ItemUpdate(UpdateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    def get_context_data(self):
        context = super(ItemUpdate, self).get_context_data()
        context["todo_list"] = self.object.todo_list
        context["title"] = "Edit item"
        return context

    def get_success_url(self):
        return reverse("todo_app:list", args=[self.object.todo_list_id])


class ListDelete(DeleteView):
    model = ToDoList
    # You have to use reverse_lazy() instead of reverse(),
    # as the urls are not loaded when the file is imported.
    success_url = reverse_lazy("todo_app:todo_list")


class ItemDelete(DeleteView):
    model = ToDoItem

    def get_success_url(self):
        return reverse_lazy("todo_app:list", args=[self.kwargs["list_id"]])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["todo_list"] = self.object.todo_list
        return context

TOTP_Web/todo_app/templates/todo_app/index.html
<!-- todo_list/todo_app/templates/todo_app/index.html -->

{% extends "base_todo.html" %}
{% block title %}Todo List{% endblock %}
{% block content %}
<!--index.html-->
{% if object_list %}
<h3>All my lists</h3>
{% endif %}
<ul>
    {% for todolist in object_list %}
    <li>
        <div
            role="button"
            onclick="location.href='{% url "todo_app:list" todolist.id %}'">
            {{ todolist.title }}
        </div>
    </li>
    {% empty %}
    <h4>You have no lists!</h4>
    {% endfor %}
</ul>
<p>
    <input
        value="Add a new list"
        type="button"
        onclick="location.href='{% url "todo_app:list_add" %}'"/>
</p>
{% endblock %}

TOTP_Web/todo_app/templates/todo_app/todo_list.html
<!-- todo_list/todo_app/templates/todo_app/todo_list.html -->
{% extends "base_todo.html" %}
{% block title %}Todo-list{% endblock %}
{% block content %}
<div>
    <div>
        <div>
            <h3>Edit list:</h3>
            <h5>{{ todo_list.title | upper }}</h5>
        </div>
        <ul>
            {% for todo in object_list %}
            <li>
                <div>
                    <divF
                        role="button"
                        onclick="location.href=
                        '{% url "todo_app:item_update" todo_list.id todo.id %}'">
                        {{ todo.title }}
                        (Due {{ todo.due_date | date:"l, F j" }})
                    </div>
                </div>
            </li>
            {% empty %}
            <p>There are no to-do items in this list.</p>
            {% endfor %}
        </ul>
        <p>
            <input
                value="Add a new item"
                type="button"
                onclick="location.href=
                '{% url "todo_app:item_add" todo_list.id %}'" />
            <input
                value="Delete this list"
                type="button"
                onclick="location.href=
                '{% url "todo_app:list_delete" todo_list.id %}'" />
        </p>
    </div>
</div>
{% endblock %}

TOTP_Web/todo_app/templates/todo_app/todoitem_confirm_delete.html
<!-- todo_list/todo_app/templates/todo_app/todoitem_confirm_delete.html -->
{% extends "base_todo.html" %}
{% block title %}Todo List{% endblock %}
{% block content %}

<h3>Delete To-do Item</h3>

<p>Are you sure you want to delete the item: <b>{{ object.title }}</b>
   from the list <i>{{ todo_list.title }}</i>?</p>

<form method="POST">
    {% csrf_token %}
    <input
        value="Yes, delete."
        type="submit">
    <input
        value="Cancel"
        type="button"
        onclick="location.href='{% url "todo_app:list" todo_list.id %}';">
</form>

{% endblock %}

TOTP_Web/todo_app/templates/todo_app/todoitem_form.html
<!-- todo_list/todo_app/templates/todo_app/todoitem_form.html -->
{% extends "base_todo.html" %}
{% block title %}Todo List{% endblock %}
{% block content %}

<h3>{{ title }}</h3>
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input
        value="Submit"
        type="submit">
    <input
        value="Cancel"
        type="button"
        onclick="location.href='{% url "todo_app:list" todo_list.id %}'">
    {% if object %}
        <input
            value="Delete this item"
            type="button"
            onclick="location.href=
            '{% url "todo_app:item_delete" todo_list.id object.id %}'">
    {% endif %}
</form>

{% endblock %}

TOTP_Web/todo_app/templates/todo_app/todolist_confirm_delete.html
<!-- todo_list/todo_app/templates/todo_app/todolist_confirm_delete.html -->
{% extends "base_todo.html" %}
{% block title %}Todo List{% endblock %}
{% block content %}
<!--todolist_confirm_delete.html-->

<h3>Delete List</h3>

<p>Are you sure you want to delete the list <i>{{ object.title }}</i>?</p>

<form method="POST">
    {% csrf_token %}
    <input
        value="Yes, delete."
        type="submit">
</form>
<input
    value="Cancel"
    type="button"
    onclick="location.href='{% url "todo_app:todo_list" %}';">

{% endblock %}

TOTP_Web/todo_app/templates/todo_app/todolist_form.html
<!-- todo_list/todo_app/templates/todo_app/todolist_form.html -->
{% extends "base_todo.html" %}
{% block title %}Todo List{% endblock %}
{% block content %}

<h3>{{ title }}</h3>
<div>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input
                value="Save"
                type="submit">
            <input
                value="Cancel"
                type="button"
                onclick="location.href='{% url "todo_app:todo_list" %}';">
        </form>
    </div>
</div>

{% endblock %}